### ISSUE TITLE
incorrect curl syntax

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/cloud-manager-setup-admin#100]
Page: [Managing your NetApp account](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-netapp-accounts.html)

Hello Team,

I believe there is a typo in the bellow curl command as '--data-raw' results in an error:

`curl --location --request POST 'https://netapp-cloud-account.auth0.com/oauth/token' \
--header 'Content-Type: application/json' \
--data-raw '{
    "grant_type": "client_credentials",
    "client_secret": "<client secret>",
    "audience": "https://api.cloud.netapp.com",
    "client_id": "<client id>"
}'
`
The error messages:

`curl: option --data-raw: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
`

When using '--data' option on its own the curl will work and I get the bearer token.

There is a topic on this on StackOverflow, though, I haven`t tested their solution yet
https://stackoverflow.com/questions/43054195/how-to-post-raw-body-data-with-curl

**Comment by netapp-bcammett** [comment]
Hi Gabor,

Thank you for submitting this issue. Rather than recreate this information, I updated the page by pointing to our API documentation, which has much better details about how to create the token for the service account.

https://docs.netapp.com/us-en/cloud-manager-automation/platform/create_service_token.html

Thanks again,
Ben
